name: Weekly Checks

on:
  #  every Monday at 4:30 AM
  # (hopefully after the 1:30 AM `depends` build has completed)
   schedule:
    - cron: '30 4 * * 1'

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        R:
          - "devel"
    uses: ./.github/workflows/reused/test.yml
    with:
      R-version: ${{ matrix.R }}
    secrets: inherit

  check:
    strategy:
      fail-fast: false
      matrix:
        R:
          - "devel"
    uses: ./.github/workflows/reused/check.yml
    with:
      R-version: ${{ matrix.R }}
      make-grouping: ${{ matrix.package }}
    secrets: inherit

  sipnet:
    strategy:
      fail-fast: false
      matrix:
        R:
          - "devel"
    uses: ./.github/workflows/reused/sipnet.yml
    with:
      R-version: ${{ matrix.R }}
    secrets: inherit
