name: Weekly Checks

on:
  #  every Monday at 4:30 AM
  # (hopefully after the 1:30 AM `depends` build has completed)
   schedule:
    - cron: '30 4 * * 1'

env:
  R_LIBS_USER: /usr/local/lib/R/site-library
  LC_ALL: en_US.UTF-8
  NCPUS: 2
  PGHOST: postgres
  CI: true

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        R:
          - "devel"
    uses: ./.github/workflows/reused/test.yml
    with:
      R-version: ${{ matrix.R }}
    secrets: inherit

  check:
    strategy:
      fail-fast: false
      matrix:
        R:
          - "devel"
    uses: ./.github/workflows/reused/check.yml
    with:
      R-version: ${{ matrix.R }}
      make-grouping: ${{ matrix.package }}
    secrets: inherit

  # ----------------------------------------------------------------------
  # SIPNET TESTS
  # ----------------------------------------------------------------------
  sipnet:
    if: github.event_name != 'issue_comment' || startsWith(github.event.comment.body, '/build')
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    strategy:
      fail-fast: false
      matrix:
        R:
          - "devel"

    services:
      postgres:
        image: mdillon/postgis:9.5
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    container: 
      image: pecan/depends:R${{ matrix.R }}

    steps:
    # checkout source code
    - name: work around https://github.com/actions/checkout/issues/766
      run: git config --global --add safe.directory "$GITHUB_WORKSPACE"
    - uses: actions/checkout@v4
      with:
        set-safe-directory: false

    # install additional tools needed
    - name: install utils
      run: apt-get update && apt-get install -y postgresql-client qpdf
    - name: install new dependencies
      run: Rscript scripts/generate_dependencies.R && cd docker/depends && Rscript pecan.depends.R

    # initialize database
    - name: db setup
      uses: docker://pecan/db:ci
    - name: add models to db
      run: ./scripts/add.models.sh

    # install sipnet
    - name: Check out SIPNET
      uses: actions/checkout@v4
      with:
        repository: PecanProject/sipnet
        path: sipnet
        set-safe-directory: false
    - name: install sipnet
      run: |
        cd ${GITHUB_WORKSPACE}/sipnet
        make

    # compile PEcAn code
    - name: build
      run: make -j1

    # run SIPNET test
    - name: integration test
      run: ./tests/integration.sh ghaction
