name : Integration Tests
on :
  # allow manual triggering 
  workflow_dispatch:
  
  # for debugging
  push:
  pull_request:

  schedule:
    # run Thursday 4:30 AM UTC
  - cron: '30 4 * * 4'    
jobs:
  test:
    runs-on: ubuntu-20.04

    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    
    container: 
      image: pecan/base:develop

    steps:
    - name: Checkout source code
      uses: actions/checkout@v3

    - name: Run tests
      run: |
        for FILE in modules/data.atmosphere/inst/integrationTests/*; do
          if [[ ! "$FILE" == *ERA5* ]]; then
            Rscript "$FILE"
          else
            echo "Skipping file : $FILE"
          fi
        done
