name : Integration Tests
on :
  # allow manual triggering 
  workflow_dispatch:
  schedule:
    # run Thursday 4:30 AM UTC
  - cron: '30 4 * * 4'    
jobs:
  test:
    runs-on: ubuntu-latest

    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    
    container: 
      image: pecan/depends:R4.1

    steps:
    - name: Checkout source code
      uses: actions/checkout@v3
    - name: Run tests
      run: |
        for FILE in modules/data.atmosphere/inst/integrationTests/*; Rscript $FILE;
    